language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=git2/index.html>' > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
  rm target/doc/index.html &&
  mv target/doc . &&
  (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
env:
  global:
    - secure: OUEJN91dVSqpWtn8uDgGQJVGr6k9PuHrtOfpIgztIHWHiEXQVvdiuobm5iPqcpiXl+LDUIpRnwrH6WLIiWQodTRvdfDx/mJ14uKTXS354V7zV9yNd4mc7AhHvV8tNl+3zJQlPir9s1FrFu+6YEMuxilFgeLRqSXoeSVprVB+Fwo=
    - secure: KgyhQ5rVcuSUxgsABVd85KDajPjLlEUDll2+z+TTZB5zdowoGgqDH/Iqp1eXqsjerh3wgR36k3E9Dhb0mLJA51pZkfX9rxXNWU+gWr3l99TIHSuVsqlYtSMTR2Fjfz3W00jL6BQTZb8PMJMRzc3HotJ2qY+nCXDeik4ifVwwW3A=
notifications:
  email:
    on_success: never
