language: rust
git:
  submodules: false

matrix:
  include:
    - rust: 1.32.0
    - rust: stable
    - os: osx
      rust: stable
      before_install:
        - export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
        - export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
    - rust: beta
    - rust: nightly

script:
  - git submodule update --init
  - cargo test --no-default-features
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml --release
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo test --features unstable;
      cargo test --manifest-path git2-curl/Cargo.toml;
    fi

notifications:
  email:
    on_success: never
