environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - set CARGO_TARGET_DIR=%APPVEYOR_BUILD_FOLDER%\target
  - rustc -V
  - cargo -V
  - git submodule update --init

build: false

test_script:
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
