environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%

  - if defined MSYS_BITS set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --target %TARGET%
  - cargo test --no-default-features --target %TARGET%
  - cargo run --manifest-path systest/Cargo.toml --target %TARGET%
